defaults:
  - default_config

ExperimentConfig:
  BC_finetuning: true
  model_path: Basis_thesis_replays
  BC_model_path:        # BC_model_path == model_path, falls BC_model_path None ist
  exp_name:
  wandb_project_name: new_finetuning_BC


  render: true
  render_all: false

  prod_mode: true
  seed: 1

  BC_learning_rate: 1e-6
  BC_weight_decay: 0.0

  resume: true
  epochs: 30                   # new (BA Parameter) 100 Epochen, BC-finetuning 70 Epochen
  warmup_epochs: 20            # new (BA Parameter) (Over 30 epochs, Î± linearly decreases to zero) (changed: 20)
  newdata: false                
  nurwins: true 
